from . import key_trigger
from . import door_open
from . import wait_command
from . import move_edu
from . import move_op
from . import find_person_edu
from . import find_person_op
from . import find_person
from . import find_object
from . import grasping_edu
from . import grasping_op
from . import put_edu
from . import put_op
from . import ask
from . import report
from . import follow_me
from . import answer
from . import str_send_wheel
